---
title: "Vaccines Markdown"
author: "Dipankar Lahiri"
date: "2025-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(ggplot2)
library(knitr)
library(psych)

options (scipen = 999)

opinion_levels <- c("Strongly disagree", "Tend to disagree", "Neither agree nor disagree", "Tend to agree", "Strongly agree")
education_levels <- c("Primary school", "Secondary school (age under 15 years old)", "GNVQ / GSVQ / GCSE/ SCE standard.", "NVQ1, NVQ2", "NVQ3/ SCE Higher Grade/ Advanced GNVQ/ GCE A/AS or similar.", "NVQ4 / HNC / HND / Bachelor's degree or similar.", "NVQ5 or post-graduate diploma.")

data_vaccines <- read_csv('../Vaccines/trust-vaccines.csv',
                          col_types = cols(
                            col_number(),
                            col_factor(),
                            col_factor(ordered = TRUE, levels = education_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels),
                             col_factor(ordered = TRUE, levels = opinion_levels)
                          ))

data_vaccines <- data_vaccines %>%
  mutate (
    across (
      .cols = c(starts_with('gov'), starts_with('vac')),
      .fns = as.numeric,
      .names = '{.col}_coded'
    )
  )

keys_list <- list (
  gov_trust = c(
    'govhonest_coded',
    'govright_coded',
    '-govunfair_coded',
    '-govignore_coded',
    '-govcautious_coded',
    '-govxbel_coded'
  ),
  vac_trust = c(
    'vacch_coded',
    'vacsafe_coded',
    'vacwork_coded'
  )
)

scores <- scoreItems(
  keys = keys_list,
  items = data_vaccines,
  totals = FALSE,
  missing = TRUE,
  impute = 'none'
)

data_vaccines <- cbind(data_vaccines, scores$scores)
```

#Demographic statistics

##Gender
```{r}
data_vaccines %>%
  count(gender_nb)


data_vaccines %>%
  ggplot (aes(x = gender_nb)) +
  geom_bar()

```

##Age

```{r}
data_vaccines %>%
  summarise (n=n(), 
             M = mean (age) %>% round (digits = 2),
             Mdn = median (age))

data_vaccines %>%
  ggplot (aes(x=age)) +
  geom_histogram()
```

##Education

```{r}
data_vaccines %>%
     count(hhedqual)

data_vaccines %>%
  ggplot(aes(x=hhedqual))+
  geom_bar() + coord_flip()
```
#Opinion statistics

```{r}
data_vaccines_opinions <- data_vaccines %>%
 select (ends_with('coded')) %>%
   lapply(
    median, na.rm = TRUE
  )

data_vaccines_opinions_median <- tibble(
  Item = data_vaccines_opinions %>% names,
  Median = data_vaccines_opinions %>% unlist
)

data_vaccines_opinions_median

data_vaccines_opinions_median %>%
  ggplot(aes(x= Item, y= Median)) + geom_point() + coord_flip()
```
```{r}
data_vaccines <- data_vaccines %>%
  mutate (
    Female = gender_nb == "Female",
    Male = gender_nb == "Male",
    Non_binary = gender_nb != "Male" & gender_nb != "Female",
    Gov_honest = govhonest_coded > 3,
    Gov_right = govright_coded > 3,
    Gov_unfair = govunfair_coded > 3,
    Gov_ignore = govignore_coded > 3,
    Gov_cautious = govcautious_coded > 3,
    Gov_xbel = govxbel_coded > 3,
    Vac_healthy = vacch_coded >3,
    Vaccines_Safe = vacsafe_coded > 3,
    Vac_work = vacwork_coded > 3
    )

data_vaccines %>%
  group_by(Female) %>%
  summarise(
    n = n(),
    Vac_Safe_Agree = sum(Vaccines_Safe, na.rm = TRUE)
  ) %>%
  mutate (
    Percentage = round (Vac_Safe_Agree / n * 100)
  )

#Tests

chisq.test(
  data_vaccines$Female,
  data_vaccines$Vaccines_Safe
)

```
```{r}
fisher.test(
  data_vaccines$Female,
  data_vaccines$Vaccines_Safe
)
```

```{r}
data_vaccines %>%
  wilcox.test(
    vacsafe_coded ~ Female,
    data = .
  )
```

```{r}
data_vaccines %>%
  t.test (
    age ~ Vaccines_Safe,
    var.equal = FALSE,
    data = .
  )
```
#Analysis with scores 

```{r}
data_vaccines %>%
  ggplot (aes(x=gov_trust, fill = Female)) +
  geom_histogram(binwidth = 0.5)

data_vaccines %>%
  ggplot (aes(x=vac_trust, fill = Female)) +
  geom_histogram(binwidth = 0.5)
```
```{r}
data_vaccines %>%
  ggplot (aes(x=gov_trust, y=vac_trust, colour = Female)) +
  geom_jitter(size = 0.5)
```

```{r}
data_vaccines %>%
  ggplot (aes(x=age, y=vac_trust, colour = Female)) +
  geom_jitter(size = 0.5)
```
#Correlations

```{r}
data_vaccines %>%
  t.test(
    vac_trust ~ Female,
    var.equal = FALSE,
    data = .
  )

data_vaccines %>%
  mutate(Female = as.numeric(Female)) %>%
  cor.test(~ vac_trust + Female, data = .)

data_vaccines %>%
  mutate(Female = as.numeric(Female)) %>%
  cor.test(~ gov_trust + Female, data = .)

data_vaccines %>%
  cor.test(~ gov_trust + age, data = .)

data_vaccines %>%
  cor.test(~ vac_trust + age, data = .)

data_vaccines %>%
  cor.test(~ gov_trust + vac_trust, data = .)


```
# Linear regression modelling

```{r}

data_vaccines %>%
  mutate (Female = Female %>% as.numeric) %>%
  lm (vac_trust ~ age + gov_trust + Female, data = .) %>%
  summary

```

```{r}

```